### ISSUE TITLE
How to configure for more than one Vite app?

### ISSUE THREAD

**Issue by angelov-a** [lhapaipai/vite-bundle#1]
Hello,

The provided config works if there's just one Vite app in the project. However, I would like to have more apps.

How can I provide multiple build directories with corresponding public paths? Thanks.

```# config/packages/pentatrion_vite.yaml
pentatrion_vite:
  # Base public path when served in development or production
  base: /build/
```

**Comment by lhapaipai** [comment]
Hi @angelov-a, if you want more than one app in your project you can specify your entry points in your `vite.config.js` file.

```js
export default {
  // ...
  build: {

    rollupOptions: {
      input: ["./assets/app.js", "./assets/other-entry-point.js"],
    },
  },
};
```
in your `public/build` you'll find all your files.
and you can reference your other point in your template : 
```twig
{% block stylesheets %}
    {{ vite_entry_link_tags('other-entry-point.js') }}
{% endblock %}

{% block javascripts %}
    {{ vite_entry_script_tags('other-entry-point.js') }}
{% endblock %}
```
but I don't believe you can provide multiple build directories with vite ? [build.outDir](https://vitejs.dev/config/#build-outdir)
not to mention the bundle, how do you do that with vite config? and for what purpose ?

**Comment by angelov-a** [comment]
Hello @lhapaipai,

Thanks for the answer!

It's not needed to have multiple build directories, since it's separate Vite projects. But they are in one Symfony project which would open the Vite apps in different twig templates. 

So the build directories would be

```
├──public
│ ├──app1
│ ├──app2
```

Would it be possible to have?
```twig
# template for app 1
{% block javascripts %}
    {{ vite_entry_script_tags('app1/main.js') }}
{% endblock %}

# template for app 2
{% block javascripts %}
    {{ vite_entry_script_tags('app2/main.js') }}
{% endblock %}
```

**Comment by lhapaipai** [comment]
Hi,
It's actually not possible to use this bundle if you have multiple build directories. I looked if i could implement it but it means search in multiple manifest files, and finally rewrite all the code. so i decided not to add this feature, sorry...

for me, if you need to have separate Vite projects and not only one project in symfony, it's the use case of the module building. so in this case you can always build this module separately and re-import it in your Symfony Vite project.

**Comment by lhapaipai** [comment]
Hi @angelov-a , this is now possible with PR #39 it will have taken time but everything happens :-)
