### ISSUE TITLE
Public services for easy DI

### ISSUE THREAD

**Issue by FluffyDiscord** [lhapaipai/vite-bundle#10]
Hello, would you mind adding your services such as that I can DI them in __constuct() instead of using painful aliases ?

Following code does not work, because you can't reference classes and I have to add special entry in config/services
```php
public function __construct(private EntrypointsLookup $entrypointsLookup)
{
}
```

![image](https://user-images.githubusercontent.com/10332247/146610706-c3498654-d483-4a16-a098-1b28d919bd76.png)

**Comment by lhapaipai** [comment]
ok @FluffyDiscord it's fixed !
