### ISSUE TITLE
Thank you & Symfony Slack

### ISSUE THREAD

**Issue by pbowyer** [lhapaipai/vite-bundle#13]
Thank you for writing this bundle - it works really well and I'm enjoying migrating my Symfony sites to Vite 😄 

I wanted to let you know I've created a #vitejs channel on the [Symfony Slack](https://symfony.com/slack) as there's starting to be regular questions about using Vite. I'll try and help people if they get stuck, and you'd be very welcome if you want to join Slack.

**Comment by lhapaipai** [comment]
Great idea, creating this channel !
Have a good day !
