### ISSUE TITLE
Upgrade to vite 2.8.x shows Entry points must be inside Vite root directory

### ISSUE THREAD

**Issue by pscheit** [lhapaipai/vite-bundle#15]
Hey there!

unfortunately i cannot upgrade to vite 2.8. with the plugin.

When I downgrade vite to 2.7.x it works as before.

My vite config looks exactly like the readme.md file

I get the error: "Entry points must be inside Vite root directory"
i debugged a bit and it resolves the relative path wrong. It resolves it to the pwd instead of pwd + config.root, that's why the error occurs

**Comment by mfehr94** [comment]
Also mentiont [3#](https://github.com/lhapaipai/vite-plugin-symfony/issues/3#issue-1128805215)

**Comment by pscheit** [comment]
sorry for that.. something is very odd. I can' see my own issue and did not see your issue... ? :/
My github issues tab says (1) and one closed

**Comment by mfehr94** [comment]
@pscheit different repository

**Comment by lhapaipai** [comment]
thank you for your feedback, the problem has been solved with version 1.2
