### ISSUE TITLE
Include publicDir: false in vite.config.js

### ISSUE THREAD

**Issue by marcelkorpel** [lhapaipai/vite-bundle#17]
When building a project for deployment I run `npm run build`, which runs `vite build`. By default, Vite will copy all assets in `/public` to the build directory. However, this is generally not what you want with the Symfony `/public` directory: apart from useless files like `index.php` it will also copy bundles in `/public/bundles`, so a directory is created. At this moment, you will run into trouble with `npm run dev`, which outputs:
```
error when starting dev server:
SystemError [ERR_FS_EISDIR]: Path is a directory: rm returned EISDIR (is a directory) /Users/xxx/Sites/project-dir/public/build/bundles
```
You can circumvent this whole copying behaviour by adding
```
publicDir: false
```
to `vite.config.js`.

Would this be a sane default to add to the README?

**Comment by well-made** [comment]
You could also just set the `publicDir` to something else like `assets/public`.

But for some reason when it copies this files using `yarn run build` (`vite build`) and I want to use `yarn run dev` (`vite`) afterwards, I get the same error.

The reason we use this publicDir is to copy images and minimize them using `vite-imagemin`. Not sure how to handle this scenario.

**Comment by lhapaipai** [comment]
Thank you @marcelkorpel, You're totally right !

**Comment by lhapaipai** [comment]
for your information, I added a new feature to `vite-plugin-symfony` v0.5.2. Vite will serve files in public directory as static files but will not copy public directory in build process. so we can enjoy the files present in public dir without its side effects.
if you don't wants this feature you can set : `symfonyPlugin({ servePublic: false })`
