### ISSUE TITLE
Bundle config being seemingly ignored

### ISSUE THREAD

**Issue by FluffyDiscord** [lhapaipai/vite-bundle#18]
Server options seems to be ignored as setting `host` to a different domain other than `localhost` does nothing.

Then browser keeps reloading because it can't connect to the websocket.
```
[vite] connecting...
​ WebSocket connection to 'ws://my.domain.local:3000/build/' failed: 
(anonymous) @ client:188
​ [vite] server connection lost. polling for restart...
 GET http://my.domain.local/build/__vite_ping 404 (Not Found)
```

My config at `config/packages/pentatrion_vite.yaml`
```yaml
pentatrion_vite:
    base: /build/
    public_dir: /public
    server:
        host: my.domain.local
        port: 3000
        https: false
```

Running the `vite` command shows that it's still listening to localhost.
```
vite v2.8.6 dev server running at:

  > Local: http://localhost:3000/build/
  > Network: use `--host` to expose

  ready in 12137ms.
```
Oddly enough, after upgrading vite from 2.7 to 2.8 and your plugin from 0.2.4 to 0.3.1 makes it that the server is suddenly slow as snail. It went from `ready in about 1s` to `ready in 12 secs` That is _insane_, any tips ? Is it scanning the whole project because the `root` is no longer `./assets` but `.` in `vite.config.js` ?

```vite.config.js
import {defineConfig} from "vite"
import symfonyPlugin from "vite-plugin-symfony"
import { svelte } from "@sveltejs/vite-plugin-svelte"
import autoPreprocess from 'svelte-preprocess'
import viteDefineEnvs from "vite-define-envs-plugin"
import { visualizer } from 'rollup-plugin-visualizer'

export default defineConfig({
    plugins: [
        symfonyPlugin(),
        svelte({
            preprocess: autoPreprocess()
        }),
        viteDefineEnvs(["NODE_ENV"], "process.env"),
        // visualizer({
        //     template: 'treemap',
        //     gzipSize: true,
        //     open: true,
        // })
    ],
    root: ".",
    base: "/build/",
    build: {
        manifest: true,
        emptyOutDir: true,
        assetsDir: "",
        outDir: "./public/build/",
        rollupOptions: {
            input: {
                app: "./assets/app.ts",
                admin: "./assets/admin.ts",
            },
        },
    },
    resolve: {
        alias: [
            {
                find: /^~.+/,
                replacement: (val) => {
                    return val.replace(/^~/, "");
                },
            },
        ],
    },
});
```

`vite-plugin-symfony`: 0.3.1
`pentatrion/vite-bundle`: 1.2.0

**Comment by lhapaipai** [comment]
hi @FluffyDiscord ,
you need to configure your custom host in your `vite.config.js` : https://vitejs.dev/config/#server-host

with `config/packages/pentatrion_vite.yaml` you configure that your twig template will generate script tags with your custom domain but vite still needs to be configured for that custom domain...

**Comment by FluffyDiscord** [comment]
Yes, I completely forgot... I am sorry for the useless issue

**Comment by lhapaipai** [comment]
no problem !!
