### ISSUE TITLE
vite.js hotreload is replaced by page reloading, if I modified the App.jsx and save it.

### ISSUE THREAD

**Issue by vikbert** [lhapaipai/vite-bundle#2]
hot-reload is not possible after integration vite-bundle. The vite dev server will trigger reloading the whole page. It can cause the problem with performance, if the page is getting complexer. It can cause the big trouble, if the page has multiple REST requests to remote APIs. 

Is there any solution for it? or I made something wrong?

**Comment by lhapaipai** [comment]
Hi @vikbert,
Thanks for your return,
I do not practice React, so you will guess that I had not done any tests with it...
Indeed there was a problem with this line
```js
import RefreshRuntime from "/@react-refresh"
```
your browser try to resolve this url **with the symfony webServer and not the vite dev server**.
With this fix, depending on configuration, this line became
```js
import RefreshRuntime from "http://localhost/build/@react-refresh"
```
and the hot reload is ok !

however the set only works for the moment with Symfony configured with a virtual host. If you try to use
```console
symfony server:start
```
to serve your symfony dev server you will have annoying page reloads.
your advice is welcome !

**Comment by vikbert** [comment]
@lhapaipai thx very much. I will have a try as you suggested.
