### ISSUE TITLE
options for vite_entry_link_tags / vite_entry_script_tags

### ISSUE THREAD

**Issue by WebMechanic** [lhapaipai/vite-bundle#28]
Salût,

both script and link elements support various attributes to improve load and execution order and as a result have an impact on page performance. 
These attributes include link prefetch, preload or script defer, async, type, nomodule etc.

Are there ways to set additional attributes to individual `vite_entry_link_tags()` and `vite_entry_script_tags()` calls so one can control how certains scripts and stylesheets are downloaded by the browser? 

I only found `$options['dependency']` in `renderScripts` apparently dealing with React and no options whatsoever for `renderLinks`

Thank you.

---

Harry Roberts (aka [csswizardry](https://csswizardry.com/)) explains this in his talk "Get your head straight".

"Get your head straight" by Harry Roberts, Web Performance Engineer
- https://csswizardry.com/ct/
- https://youtu.be/MHyAOZ45vnU
- https://podrocket.logrocket.com/head-tag-javascript-harry-roberts

**Comment by WebMechanic** [comment]
_Depicted HTML below represents the expected rendered results but w/o hashes._

## link media=""

The ability to pass attributes to `vite_entry_link_tags` would allow the use of the `media` attribute. A feature available since the invention of media queries and ignored after JS devs believed inlining CSS in their component code is the only way to go:

```html
<link rel="stylesheet" href="dark.css" media="screen and (prefers-color-scheme: dark)" />
<link rel="stylesheet" href="light.css" media="screen and (prefers-color-scheme: light)" />
<link rel="stylesheet" href="dead-trees.css" media="print" />
<link rel="stylesheet" href="small-screen.css" media="screen and (max-width:36em)" />
<link rel="stylesheet" href="huge-screen.css" media="screen and (max-width:128em)" />
```
Separating themes is more performant than having all styles in a single `theme.css` wrapping each within a `@media` query. The browser could then decide upfront which style-sheet is relevant and will load and parse less code -- and cache the files individually. _The other style-sheets will be downloaded and cached eventually. _
They become instantly available from cache if needed (i.e. toggle dark/light mode, orientation or resize the browser window, print page or save to pdf).

- https://caniuse.com/mdn-html_elements_link_media

## link rel="modulepreload"

To speed up script dependencies when using ESM, `rel="modulepreload"` becomes very handy.
Consider this setup with `main.js`:
```js
// /static/main.js
import Header from '/static/Header.js';
...

// /static/Header.js
import Logo from '/static/Logo.js';
import Link from '/static/Link.js';
...

// /static/Logo.js
import Img from '/static/Img.js';
```
If you simply add a `<script src="/static/main.js" type="module">` onto the page, the app can’t start working before all modules are downloaded, this makes the app load longer.
`<link rel="modulepreload">` solves this.
```html
<link rel="modulepreload" href="/static/Header.js" />
<link rel="modulepreload" href="/static/Logo.js" />
<link rel="modulepreload" href="/static/Image.js" />
<!-- if the module belongs to e.g. a service worker: -->
<link rel="modulepreload" href="/static/Header.js" as="serviceworker" />
```
Deciding what goes into a `modulepreload` link would (still) require manual labour, but it'd be worth doing so for very large components.

- https://caniuse.com/link-rel-modulepreload

**Comment by lhapaipai** [comment]
Bonjour @WebMechanic,
I have implemented this feature. If you have any feedback don't hesitate...
