### ISSUE TITLE
Enable Discussions

### ISSUE THREAD

**Issue by WebMechanic** [lhapaipai/vite-bundle#29]
Salût @lhapaipai ,

would you mind to enabled "Discussions" for both this repo and the Vite plugin? 
Then users of this package could exchange ideas, help each other, and talk about possible extensions, settings, tweaks ... 

I believe to be on par with `Symfony Encore`, a few small things are still missing that may however not necessarily require creating a new issue.

Thank you!

**Comment by lhapaipai** [comment]
it's done !
