### ISSUE TITLE
Roadmap v1

### ISSUE THREAD

**Issue by ocjojo** [lhapaipai/vite-bundle#3]
Hi @lhapaipai, thank you for creating this package. Some questions I have before using it:
Do you consider this package a demo or is it supposed to be open source and used by the community?
Would you be willing to add a license?
Can you provide a rough timeline when this package will be production ready?
Which features are missing until you would consider releasing a v1.x?
I might also be able to contribute if you would be willing to accept help.

Thank you!

**Comment by lhapaipai** [comment]
Hi @ocjojo, thank you for your interest of the bundle.
I use this bundle in my production projects.
I was waiting a little time before upgrading to version 1 in case I needed to make any breaking changes.

I my use case (vite with vuejs, svelte, vanilla javascript) I consider this package production ready. As I do not use react I can not guarantee you that it is stable with this library. the code is somewhat different with the hot reload and I haven't done any in-depth testing.

For the moment I see 1 thing to improve.

If you import asset in your application 
```js
// example with VueJS
<template>
  <img alt="Vue logo" src="./assets/logo.png" />
  <HelloWorld msg="Hello Vue 3 + Vite" />
</template>
```

```js
//vite.config.js
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()],
  base: "/build/",
});

```

the img will be transformed to `<img alt="Vue logo" src="/build/assets/logo.png" />` and will return a 404 error in a development environment.

One solution could be to make a plugin who create a symlink from `public/build` to `src`
in development only and destroy this link when you stop the dev server.
But it might be dangerous. If for some reason the symlink is not removed in build time : all the `public/build` is cleaned and you lose ALL your `src` files...

So, for the moment I prefer don't use this fonctionnality...
If you have idea to contribute, Pull requests are welcome !
