### ISSUE TITLE
Provide a solution for "vite-plugin-react can't detect preamble. Something is wrong."

### ISSUE THREAD

**Issue by bohanyang** [lhapaipai/vite-bundle#32]
Thanks for writing this bundle!

I'm trying to use it with React but this error occurred when using dev server.

As what discussed in https://github.com/vitejs/vite/issues/1984,
it seems that Vite cannot inject a piece of code used for React hot reloading,
since the HTML is generated by PHP.

After adding these code in Twig template, things worked.

```
        {% block javascripts %}
            <script type="module">
                import RefreshRuntime from "/build/@react-refresh"
                RefreshRuntime.injectIntoGlobalHook(window)
                window.$RefreshReg$ = () => {}
                window.$RefreshSig$ = () => (type) => type
                window.__vite_plugin_react_preamble_installed__ = true
            </script>
            {{ vite_entry_script_tags('app') }}
        {% endblock %}
```

The code coming from: https://github.com/vitejs/vite/blob/d9f6dc0ecfc0f6a1c394c8645f474cb32a9e447a/packages/plugin-react/src/fast-refresh.ts#L31-L37

Should we provide a solution for this issue (not a bug of Vite though) out-of-the-box? That would help many React developers.

Thanks!

**Comment by lhapaipai** [comment]
hi, @bohanyang your mentioned issue can be managed with the `dependency` option ?
```twig
{% block javascripts %}
    {{ vite_entry_script_tags('app', { dependency: 'react' }) }}
{% endblock %}
```
https://github.com/lhapaipai/vite-bundle#installation

**Comment by bohanyang** [comment]
Oh sorry! Didn't notice that option maybe just because I'm looking at the Migration doc.

You're welcome!
