### ISSUE TITLE
nonce attribute missing

### ISSUE THREAD

**Issue by DavidPetrasek** [lhapaipai/vite-bundle#35]
`{{ vite_entry_script_tags( 'app',
    {
        attr:  { nonce: 'my-nonce'}
    }) 
}}`

This adds a nonce, but only to app.js script:
```
<script src="https://127.0.0.1:5173/build/@vite/client" **nonce is expected here** type="module"></script>
<script src="https://127.0.0.1:5173/build/assets/app.js" nonce="" type="module"></script>
```

**Comment by lhapaipai** [comment]
Hi @DavidPetrasek, I think nonce is not expected for development ? and the `/build/@vite/client` is a dev only script.

https://github.com/lhapaipai/vite-bundle/blob/7cd8acc6eac2f5ab402736c249ec430e67b1745e/src/Asset/EntrypointRenderer.php#L46

If you don't share my opinion, can you give me a use case ?

**Comment by DavidPetrasek** [comment]
Yes, nonce it's not needed for development, but in my opinion it's better to make the development version as close to the production version as possible, so that's why I don't want to disable csp nonce when in development mode. I solved it like this:
```
{% block javascripts %}

    {% if app.environment is same as('prod') %}
    
        {{ vite_entry_script_tags('app',
        {
            attr: 
            {
                nonce: csp_nonce
            }
        }) 
        }}
    {% elseif app.environment is same as('dev') %}
    
    	<script src="https://127.0.0.1:5173/build/@vite/client" nonce="{{ csp_nonce }}" type="module"></script>
        <script src="https://127.0.0.1:5173/build/assets/app.js" nonce="{{ csp_nonce }}" type="module"></script>
    
    {% endif %}
    
{% endblock %}
```

**Comment by DavidPetrasek** [comment]
I would label this issue as label:enhancement
