### ISSUE TITLE
Asset versioning with other bundles not working

### ISSUE THREAD

**Issue by crtl** [lhapaipai/vite-bundle#47]
When using the `ViteAssetVersionStrategy` it will resolve the "wrong" host url in dev environments when using other bundles in dev environment.
I was trying to install [Nelmio/ApiDocBundle](https://github.com/nelmio/NelmioApiDocBundle) which loads static assets from `public/bundles/nelmioapidoc` but the `ViteAssetVersionStrategy` resolves the path to `127.0.1:3000/build/bundles/nelmioapidoc` ($origin . $host . $path).

The problem comes from [`ViteAssetVersionStrategy::getassetsPath#L79-85`](https://github.com/lhapaipai/vite-bundle/blob/e2093627359773ce97a6f05be7af38e08afc3255/src/Asset/ViteAssetVersionStrategy.php#LL79C1-L85C10)

```php
if (false !== $this->manifestData) {
            if (isset($this->manifestData[$path])) {
                return $this->build['base'].$this->manifestData[$path]['file'];
            }
        } else {
            return $this->entrypointsData['viteServer']['origin'].$this->entrypointsData['viteServer']['base'].$path;
        }
```

As a workaround I had to implement my own version strategy using the following class:
```php
<?php

namespace App\Asset;

use Pentatrion\ViteBundle\Asset\ViteAssetVersionStrategy;

class CustomAssetVersionStrategy extends ViteAssetVersionStrategy
{

    public function getVersion(string $path): string
    {
        if (str_starts_with($path, "bundles")) return $path;

        return parent::getVersion($path);
    }

    public function applyVersion(string $path): string
    {
        if (str_starts_with($path, "bundles")) return $path;
        return parent::applyVersion($path);
    }

}

```

**Comment by lhapaipai** [comment]
Hi @crtl,
ViteAssetVersionStrategy is directly associated to files built with vite, so you can't use ViteAssetVersionStrategy for another bundle assets resolution.

As a workaround I think you can configure multiple assets resolution strategies in your `config/packages/framework.yaml`

```yaml
    assets:
        packages:
            vite:
                version_strategy: 'Pentatrion\ViteBundle\Asset\ViteAssetVersionStrategy'
            nelmio:
                version_strategy: null
```

```twig
<body>
    <img src="{{ asset('assets/images/avatar.jpg', 'vite') }}" />

    <img src="{{ asset('path-to-your-nelmio-api-asset/file.jpg', 'nelmio') }}" />

</body>
```
Symfony documentation
- [multiple asset strategies](https://symfony.com/doc/current/reference/configuration/framework.html#packages)
- [custom strategy](https://symfony.com/doc/current/frontend/custom_version_strategy.html)
