### ISSUE TITLE
Conditional imports generate modulepreloads for everything

### ISSUE THREAD

**Issue by thor-juhasz** [lhapaipai/vite-bundle#55]
The `vite_entry_script_tags` twig function adds modulepreload links for conditional imports (`if (condition) { import('some-module.ts'); }`).
This should probably not happen, since the whole point of conditional imports is to avoid loading the resource at all when it's not needed.

**Comment by lhapaipai** [comment]
Hi @thor-juhasz, you're totally right. I fix this and add `preloadDynamicImports` option to `vite_entry_link_tags` if someone still wanted this behavior https://symfony-vite.pentatrion.com/guide/twig-functions.html#vite-entry-link-tags

**Comment by thor-juhasz** [comment]
May I suggest avoiding breaking changes in the default behvaior though.
Have the default value for `preloadDynamicImports` as `true`, until you release the next major version?

**Comment by thor-juhasz** [comment]
Ah I missed that you were making a major anyway.
I did have a look at how this bundle generates the module preloads.. I was under the impression that this block generates the preloads for "all" dependencies.. Not just the dynamically imported ones.
Won't this stop all module preloads completely?

**Comment by lhapaipai** [comment]
There'is no breaking changes,
`preloadDynamicImports` is only available in the v4.x release (11-07-2023)

**Comment by lhapaipai** [comment]
Yes you are right, it must be fixed... I reopen the issue

**Comment by thor-juhasz** [comment]
May I suggest a way to resolve this:

`vite-plugin-symfony` generates the `entrypoints.json`. In each entrypoint, you could introduce a new key, `dynamicImports`, which naturally, will list all the dynamic imports.

Then, in this bundle, if `preloadDynamicImports` is `true`, add the dynamic imports to the list of modules to be preloaded.

But as you are already in a new major release, this is considered a breaking change.
So, having `true` as the default value for this option avoids unexpected behavior from those that upgrade from `v4.0.0` to `v4.1.0` (assuming that would be the version that implements this).

And finally, I suggest releasing v4.0.2 which reverts v4.0.1 since:
- it's a patch version but implements a feature (does this project follow semver?)
- the feature does not behave as the option name suggests (removing all module preloads as opposed to only dynamic ones)
- the default behavior changes the behavior from v4.0.0 (breaking change)

**Comment by lhapaipai** [comment]
thank you for your feedback, I have just developed the patch which follows your advice, I am thinking of putting it in a 4.0.2 which fixes a bug since the release date of the 4.0.0 is from this morning.

**Comment by lhapaipai** [comment]
I try to follow semver as much as possible but until recently imports and dynamic imports were not preloaded at all due to a bug. Apart from you, I don't think anyone else noticed... I guess it won't be so disturbing ?

**Comment by thor-juhasz** [comment]
Possible.. 😅 but most devs never end up interacting with a repository even if they find issues, just hoping others take care of it (I'm guilty of that myself as well). 1500 weekly downloads (according to npm) is still rather low (webpack-encore with 160k) so..... 🤷🏼‍♂️

**Comment by lhapaipai** [comment]
yes we are not yet at the level of webpack-encore :smile:
