### ISSUE TITLE
Cannot access offset of type string on string

### ISSUE THREAD

**Issue by drazik** [lhapaipai/vite-bundle#58]
I just updated the bundle from v3.3.1 to v4.0.2 on my project with `composer require 'pentatrion/vite-bundle:^4.0'`. But now I get the following error:

![image](https://github.com/lhapaipai/vite-bundle/assets/1606068/d81ac813-a898-4853-b6fa-9348cd16f939)

I reduced my vite config to the bare minimum:

```js
import { defineConfig } from "vite"
import symfonyPlugin from "vite-plugin-symfony"
import react from "@vitejs/plugin-react"
import { fileURLToPath, URL } from "node:url"

export default defineConfig({
	plugins: [react(), symfonyPlugin()],
	build: {
		rollupOptions: {
			input: {
				"generation-add": "./assets/js/pages/generation/add/index.tsx",
			},
		},
	},
	server: {
		origin: "http://localhost:3000",
		port: 3000,
		host: "0.0.0.0",
	},
	resolve: {
		alias: {
			app: fileURLToPath(new URL("./assets/js", import.meta.url)),
		},
	},
})
```

Here is how I call the `vite_entry_link_tags` and `vite_entry_script_tags` functions (`templates/base.html.twig` file):

```twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        {% block stylesheets %}
          {{ vite_entry_link_tags("generation-add") }}
        {% endblock %}

        {% block javascripts %}
            <script type="text/javascript">
                window.pageProps = {{ (pageProps ?? '{}')|raw }};
            </script>
            {{ vite_entry_script_tags("generation-add", { dependency: "react" }) }}
        {% endblock %}
    </head>
    <body>
        {% block body %}<div id="app"></div>{% endblock %}
    </body>
</html>
```

I also tried v4.0.1 and v4.0.0 and still got the same issue. v3.3.1 works fine. Did I do something wrong on the upgrade process? Is there any upgrade guide?

**Comment by lhapaipai** [comment]
hi @drazik, have you update the `vite-plugin-symfony` ? vite-bundle v4.0.x need vite-plugin-symfony v4.0.x (v4 change the entrypoints.json file)

**Comment by drazik** [comment]
It fixes the issue! Thanks a lot @lhapaipai :heart:
