### ISSUE TITLE
Broken path on Windows - easy to fix

### ISSUE THREAD

**Issue by FluffyDiscord** [lhapaipai/vite-bundle#6]
Using this bundle under Windows creates an issue where windows has backward slashes, while generally forward slashes should be used. Thus running into the issue below:

```
$ vite
C:\Users\Mossshine\intranet-extended\assets\app.ts
C:/Users/Mossshine/intranet-extended/assets
Entry points must be inside Vite root directory
```
at configResolver.ts line 78

Changing configResolver.ts line 75 from
```
const entryAbsolutePath = resolve(cwd(), entryPath);
```
to
```
const entryAbsolutePath = resolve(cwd(), entryPath).replace(/\\/g, '/');
```

fixes this issue.

**Comment by lhapaipai** [comment]
Thanks @FluffyDiscord, I took your advice !
