### ISSUE TITLE
Question about integrating vite plugin checker

### ISSUE THREAD

**Issue by aszenz** [lhapaipai/vite-bundle#63]
I want to integrate https://vite-plugin-checker.netlify.app/ to check typescript errors actively while the dev server is running, by default this plugin shows errors in both terminal and web ui but for traditional back-ends like symfony an additional file needs to be included:

https://vite-plugin-checker.netlify.app/faq/integration.html#overlay-does-not-display-in-development-mode

Is their a way to auto inject this file where-ever we use `vite_entry_script_tags`?

**Comment by lhapaipai** [comment]
Hi @aszenz,
I added a twig function `vite_mode` who can do the job. check the documentation:
https://symfony-vite.pentatrion.com/guide/twig-functions.html#vite-mode
I added an example especially for you...

**Comment by lhapaipai** [comment]
If you need more information (vite port/host) you can create your own twig functions : https://github.com/lhapaipai/vite-bundle/issues/10

**Comment by aszenz** [comment]
> Hi @aszenz, I added a twig function `vite_mode` who can do the job. check the documentation: https://symfony-vite.pentatrion.com/guide/twig-functions.html#vite-mode I added an example especially for you...

Thanks, I ended up creating wrapper twig functions to handle embedding the plugin checker.

Leaving the code here if any one is interested:

```php
<?php

declare(strict_types=1);

namespace App\CommonBundle\Twig;

use Pentatrion\ViteBundle\Asset\EntrypointRenderer;
use Pentatrion\ViteBundle\Asset\EntrypointsLookup;
use Twig\Extension\AbstractExtension;
use Twig\TwigFunction;

/**
 * Wrapper to get style/script links from our current front-end build system.
 */
final class FrontendBuildExtension extends AbstractExtension
{
    public function __construct(
        private EntrypointsLookup $entrypointsLookup,
        private EntrypointRenderer $entrypointRenderer,
    ) {
    }

    public function getFunctions(): array
    {
        return [
            new TwigFunction('build_entry_script_tags', $this->renderScriptTags(...), ['is_safe' => ['html']]),
            new TwigFunction('build_entry_link_tags', $this->renderLinkTags(...), ['is_safe' => ['html']]),
        ];
    }

    public function renderScriptTags(string $entryName, array $options = [], string $buildName = null): string
    {
        $scripts = $this->entrypointRenderer->renderScripts($entryName, $options, $buildName);
        if ('dev' !== $this->entrypointRenderer->getMode($buildName)) {
            return $scripts;
        }

        $viteServer = $this->entrypointsLookup->getViteServer();
        $checkerPluginModuleSrc = $viteServer['origin'].$viteServer['base'].'@vite-plugin-checker-runtime-entry';

        return <<<HTML
            $scripts
            <script type="module" src="$checkerPluginModuleSrc"></script>
        HTML;
    }

    public function renderLinkTags(string $entryName, array $options = [], string $buildName = null): string
    {
        return $this->entrypointRenderer->renderLinks($entryName, $options, $buildName);
    }
}

```
