### ISSUE TITLE
Outputting a single file per entrypoint doesn't work

### ISSUE THREAD

**Issue by aszenz** [lhapaipai/vite-bundle#64]
I would like to have one js file per entrypoint (input) in my final build, as per https://symfony-vite.pentatrion.com/guide/tips.html#one-file-by-entry-point I should set `manualChunks` to `undefined` but that didn't work for me on vite 4.0 and symfony 6.3, I see many js files being imported as before.

Vite config:
```js
import { defineConfig } from 'vite';
import symfonyPlugin from 'vite-plugin-symfony';
import react from '@vitejs/plugin-react';
import tsconfigPaths from 'vite-tsconfig-paths';
import checker from 'vite-plugin-checker';
import elmPlugin from 'vite-plugin-elm';

export default defineConfig({
    plugins: [
        checker({
            // e.g. use TypeScript check
            typescript: true,
            // eslint: true
        }),
        elmPlugin(),
        react(),
        symfonyPlugin(),
        tsconfigPaths(),
    ],
    publicDir: false,
    base: '/build',
    build: {
        outDir: '../public/build',
        assetsDir: './',
        emptyOutDir: true,
        sourcemap: true,
        rollupOptions: {
            input: {
             // multiple inputs here
              app1: './App1/index.ts',
              app2: './App2/index.ts'
            },
            output: {
              manualChunks: undefined,
            },
        },
    },
});
```

I would like to just see everything bundled up in `app1.js`, `app2.js`

Related issues:
https://github.com/vitejs/vite/issues/12203

Maybe it relates to an upstream issue in rollup which vite uses internally for bundling:
https://github.com/rollup/rollup/issues/2756

**Comment by lhapaipai** [comment]
I understand, it sometimes happens that rollup makes groupings that we don't like. unfortunately `vite-plugin-symfony` won't be able to do anything about it. I advise you to create your own `manualChunks` function who will solve your constraints.
Good day

**Comment by aszenz** [comment]
> I understand, it sometimes happens that rollup makes groupings that we don't like. unfortunately `vite-plugin-symfony` won't be able to do anything about it. I advise you to create your own `manualChunks` function who will solve your constraints.
> Good day

Updated the docs in https://github.com/lhapaipai/symfony-vite-docs/pull/1 to reflect the same
