### ISSUE TITLE
`assetsInlineLimit` must be set to 0 by default

### ISSUE THREAD

**Issue by TeChn4K** [lhapaipai/vite-bundle#66]
Hello there,

I think the `build.assetsInlineLimit` parameter should be set to 0 by default. Or the documentation should mention it.

Otherwise, even with `import.meta.glob(["../images/**"]);`, all assets less than 4kb will be inlined, and will not be available in the manifest and build folder. `{{ asset('assets/images/small-asset-less-than-4kb.png') }}` will fail.

Thanks for this very useful bundle, and a great and clean documentation !

**Comment by thor-juhasz** [comment]
I suggest documenting it. Changing the config value can result in a breaking change.

**Comment by lhapaipai** [comment]
he @TeChn4K and @thor-juhasz ,
I'm agree with you @thor-juhasz, so I therefore preferred to document this issue and its solution :
assets section : https://symfony-vite.pentatrion.com/guide/assets.html#symfony-asset-component
troubleshooting section : https://symfony-vite.pentatrion.com/guide/troubleshooting.html#troubleshooting
