### ISSUE TITLE
Feature Request: Add Event to allow for dynamic attributes

### ISSUE THREAD

**Issue by GALPR** [lhapaipai/vite-bundle#73]
The injected script and link tags currently can be extended with custom attributes using the `script_attributes` and `link_attributes` configuration options.  
This is great for simple and static values but won't work if some computation is neccessary before specifying the attributes value.  
I would propose adding a `RenderAssetTagEvent` similar to [webpack-encore-bundle](https://github.com/symfony/webpack-encore-bundle/blob/2.x/src/Event/RenderAssetTagEvent.php).  
Otherwise it's impossible for me to add a nonce attribute with a dynamic value if I understand correctly.

wdyt?

__Usage example__
```php
<?php

namespace App\EventSubscriber;

use App\Service\NonceService;
use Pentatrion\ViteBundle\Event\RenderAssetTagEvent;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

class ViteTagsSubscriber implements EventSubscriberInterface
{
    public function __construct(
        private readonly NonceService $nonceService,
    ) {}

    public static function getSubscribedEvents(): array
    {
        return [
            RenderAssetTagEvent::class => 'onRenderAssetTag',
        ];
    }

    public function onRenderAssetTag(RenderAssetTagEvent $event): void
    {
        if ($event->isScriptTag()) {
            $event->setAttributes([
                'defer' => true,
                'nonce' => $this->nonceService->getNonce(),
            ]);
        }
    }
}
```

**Comment by GALPR** [comment]
@lhapaipai Any input on this?

**Comment by lhapaipai** [comment]
hi @GALPR, I think it's a good idea,
PR are welcome :smile:
else I will add this feature when I have time.

**Comment by lhapaipai** [comment]
Added in version 5.0.0.
[Migration v4 -> v5](https://symfony-vite.pentatrion.com/extra/migration.html#from-v4-x-to-v5-x)
[Custom attributes](https://symfony-vite.pentatrion.com/guide/custom-attributes.html)

Good evening !

**Comment by GALPR** [comment]
Thank you so much! 🙂

**Comment by GALPR** [comment]
Sorry to bother again, but would it be possible to also dispatch this event for the `@vite/client`? For the other script and link tags it works perfectly, but I also need to add a nonce attribute to the vite client script, but it doesn't seem like this is possible currently.

**Comment by lhapaipai** [comment]
Hi @GALPR, and what do you think about inline script tags ? if so would it be useful to make the content available ?

**Comment by GALPR** [comment]
I think it would always be useful to be able to add custom attributes to the generated tags. Especially when a strict Content-Security-Policy prevents any scripts from running except those with a correct nonce value. I am currently working on a project where I have to work around those requirements with any scripts that are loaded. So yes, I think this would be great,

**Comment by lhapaipai** [comment]
fixed in version 6, check the [migration](https://symfony-vite.pentatrion.com/extra/migration.html).

version 6 is a big refactorisation. you'll have a [RenderAssetTagEvent](https://symfony-vite.pentatrion.com/guide/custom-attributes.html) more flexible.

**Comment by GALPR** [comment]
Thank you! That looks like exactly what I need
