### ISSUE TITLE
[Question] CORS error when using HTTPS

### ISSUE THREAD

**Issue by not-a-lot** [lhapaipai/vite-bundle#8]
Hi,

I am new to using Vite.js and your bundle, and I’ve just tried loading an example, which works using HTTP for the Vite dev server, except that I get unwanted page reloads.

To serve my Symfony website project, I am not using the Symfony local server, but Apache, with HTTPS because I needed it for some features.

Since you say in your README that we should use the same HTTP or HTTPS protocol for both, I enabled https like you explain, but when I do that, my page can’t load resources from the Vite dev server anymore. This is what is shown in the Firefox console :

```
Blocage d’une requête multiorigine (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://localhost:3000/build/@vite/client. Raison : échec de la requête CORS. Code d’état : (null).
L’URI de la source du module n’est pas autorisé dans ce document : « https://localhost:3000/build/@vite/client ».
Blocage d’une requête multiorigine (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://localhost:3000/build/js/ol6_example.js. Raison : échec de la requête CORS. Code d’état : (null).
L’URI de la source du module n’est pas autorisé dans ce document : « https://localhost:3000/build/js/ol6_example.js ».
```

`ol6_example.js` is the module I am including in my Symfony template with `{{ vite_entry_script_tags('js/ol6_example.js') }}`

In my `vite.config.js` file, I tried setting `server.cors`, but the Vite.js documentation states that any origin is already allowed by default, so I didn’t expect it to change anything.

```js
export default defineConfig({
    server: {
        https: true,
        cors: true,
    //...
```

Do you have an idea how can I fix this problem? Thank you

**Comment by lhapaipai** [comment]
Hello,

I think you have to specify valid certificates for your vite dev server :
you can use mkcert : https://github.com/FiloSottile/mkcert

```console
mkcert -install
mkcert -key-file certs/vite.key.pem -cert-file certs/vite.crt.pem localhost 127.0.0.1
```

```js
import fs from "fs";

export default defineConfig({
    server: {
        https: {
          key: fs.readFileSync('certs/vite.key.pem'),
          cert: fs.readFileSync('certs/vite.crt.pem'),
        },
        cors: true,
    //...
```

**Comment by not-a-lot** [comment]
> Hello,
> 
> I think you have to specify valid certificates for your vite dev server : you can use mkcert : https://github.com/FiloSottile/mkcert
> 
> …

Thank you, that worked ! I didn’t need to use mkcert, I just reused the localhost certificate and key I had already made for development, but it seems simpler to use mkcert than to create the certificates and keys with the tutorial I had found, so thanks for telling me about it too 🙂
