### ISSUE TITLE
Not compatible with PHP 7.4 as defined in composer.json

### ISSUE THREAD

**Issue by martinfobian** [lhapaipai/vite-bundle#82]
### vite-bundle version

6.4.3

### vite-plugin-symfony version

6.4.3

### your OS, Symfony version, PHP version, Node version

PHP 7.4

### Description

EntrypointRenderer.php and Tag.php use `mixed` return type, which isn't available until PHP 8.0, but composer/packagist report compatibility with PHP 7.4

### How to reproduce

Require composer package in PHP 7.4 will install v6.4.3 which isn't compatible.

`An exception has been thrown during the rendering of a template ("Return value of Pentatrion\ViteBundle\Service\EntrypointRenderer::renderTags() must be an instance of Pentatrion\ViteBundle\Service\mixed, string returned").`

### Possible Solution

Maybe remove return type in those two classes or drop support for PHP 7.4.

**Comment by lhapaipai** [comment]
wow you are totally right. as no one had reported this issue before I imagine that no one uses this bundle with php < 8 so I'm going to increase the compatibility to php 8.0 that will also allow us to do some nice refactoring...

**Comment by lhapaipai** [comment]
fixed : https://github.com/lhapaipai/symfony-vite-dev/commit/e04f4216ce58e191d1a0fd8b2d610363e867f301
