### ISSUE TITLE
Add a way to set link header on specific entries

### ISSUE THREAD

**Issue by HugoImaios** [lhapaipai/vite-bundle#83]
### Description

Hello !

Using `preload: link-header` is great but it adds too much in the link header in my opinion.
To add only specific entries, I tried two solutions:

- use different bundle configurations (a regular one, and one for addingto  link header) as per [the doc](https://symfony-vite.pentatrion.com/guide/multiple-configurations.html#bundle-configuration) but it's not possible, because the `preload` config entry is not available as per multiple configuration (it's only available on root configuration) as per [the configuration file on github lol](https://github.com/lhapaipai/vite-bundle/blob/main/src/DependencyInjection/Configuration.php)
- use `RenderAssetTagEvent` as per [the doc](https://symfony-vite.pentatrion.com/guide/custom-attributes.html#subscribe-to-renderassettagevent-%F0%9F%A7%A9) . It worked, by adding a custom "i-want-that-in-link-header" attr, and in the `RenderAssetTagEvent` subscriber, checking for this attribute and adding the ref attribute to link header via the SF weblink component

The second solution is not that bad, but it would be nice to have another associative array of options next to `attr` to avoid messing with the existing and legitimates attributes.
But imo, the best solution would be to have the `preload: link-header` available on "sub" configurations.

Let me know what you think about it, and if you have any questions,

Hugo

**Comment by lhapaipai** [comment]
Hi @HugoImaios,
I think I would lean more towards the 2nd solution. your expectation is precise and it seems to me that the first solution provides an answer but in many cases will not be sufficient while the second would at least have the merit of providing a solution for all cases. Indeed this does not protect us from modifying existing attributes, but I do not think that this is a problem **unless we wish to define headers different from the html attributes**. Are there any cases where this could happen?

**Comment by HugoImaios** [comment]
Indeed I'm not sure it's a problem, but I'm not very comfortable with the idea of adding an attribute "i-want-this-in-link-header" just to flag this tag and not use the attribute. (in fact, I even remove it for the tag in my RenderAssetTagEvent)

**Comment by HugoImaios** [comment]
I think that the best solution we be to put it in a separate parameter called something like `contextOptions`, next to `attr` which would be clearly used only for html attributes.

**Comment by lhapaipai** [comment]
I @HugoImaios 

I am happy to announce that version 7 has been released who solve the issue we talked about...

```diff
class Tag
{
+   public bool $renderAsTag = true;
+   public bool $renderAsLinkHeader = false;

    public function __construct(
        private string $tagName,
        private array $attributes = [],
        private string $content = '',
+       private string $origin = '',
        string $preloadOption = 'link-tag'
    ) {
        // ...
    }
}
```

check the doc for more details [custom attributes](https://symfony-vite.pentatrion.com/guide/custom-attributes.html).

v7 integrates some breaking changes with v6 so take the time to look at the doc on [migration](https://symfony-vite.pentatrion.com/extra/migration.html) to update the recipe, etc...

Have a good day
feel free to close this issue if all is ok !

**Comment by HugoImaios** [comment]
Hello Hugues,
Merci pour le suivi ! Je vais regarder de plus près cette version 7 qui m'a l'air top !
Bonne journée :)

**Comment by HugoImaios** [comment]
Hello ! Tu as bien fait, j'ai été absorné sur d'autres sujets ces derniers temps, je garde ça sous le coude et rouvrirait une autre Issue si besoin :
