### ISSUE TITLE
Deprecation of the "configs" option

### ISSUE THREAD

**Issue by julien-lmnr** [lhapaipai/vite-bundle#84]
### vite-bundle version

6.4.2

### vite-plugin-symfony version

6.4.2

### your OS, Symfony version, PHP version, Node version

linux, symfony 7.0.3, php 8.3, node 20.11

### Description

Hey,

I have a depreciation warning popping up on my application with the message:
`Since pentatrion/vite-bundle 6.0.0: The "configs" option is deprecated. Use "configs" instead.`

Already, the message is weird :sweat_smile:
It seems to come from the configuration in the `packages/pentatrion_vite.yaml` file. In the documentation, it is stated that you need to have a "builds" key with the different configurations. I changed that to the "configs" key because it wasn't working.

So, I don't understand why I'm getting this depreciation.

Thanks for your work.

### How to reproduce

By creating a multiple configuration.

**Comment by lhapaipai** [comment]
you're right... it is therefore `configs` that must be used and `builds` which is deprecated. fixed in v6.4.3
