### ISSUE TITLE
Custom controller for Symfony UX Chart JS doesn't receiver events anymore

### ISSUE THREAD

**Issue by Gerben321** [lhapaipai/vite-bundle#85]
So I've moved from Webpack to Vite with this great bundle. Only thing I can't seem to be able to fix is the custom controller that I have for my ChartJS. It's all following the Symfony standards, I followed the adaptation from this bundle. In my connect() function I had these two listeners setup:
```
this.element.addEventListener('chartjs:pre-connect', this._onPreConnect);
this.element.addEventListener('chartjs:init', this._onInit);
```
These are no longer fired. The connect() function is still called, but I don't know how to set the options to my Chart from there. Everything is set to eager loading, like in the docs. Is it too late? Are the events changed? I'm not sure how to debug this.

I got these events from following this: https://symfony.com/bundles/ux-chartjs/current/index.html#using-plugins

The events are still triggered in the HTML, so I'm thinking the controller is attached too late or something?

**Comment by lhapaipai** [comment]
Hi @Gerben321,
After inspecting the chartjs stimulus controller from Symfony UX. I can give you some advices.

```twig
{{ render_chart(chart) }}
{# render #}
<canvas data-controller="symfony--ux-chartjs--chart" data-symfony--ux-chartjs--chart-view-value="..."></canvas>

{{ render_chart(chart, {'data-controller': 'mychart'}) }}
{# render #}
<canvas data-controller="mychart symfony--ux-chartjs--chart" data-symfony--ux-chartjs--chart-view-value="..."></canvas>
```

so with `render_chart(chart, {'data-controller': 'mychart'})` there are 2 independant controllers affected to `<canvas />` element : https://stimulus.hotwired.dev/reference/controllers#multiple-controllers : `symfony--ux-chartjs--chart` and `mychart`
    
if you define a `mychart_eagercontroller.js`

```js
// assets/controllers/mychart_eagercontroller.js

import { Controller } from '@hotwired/stimulus';

export default class extends Controller {
    connect() {
        this.element.addEventListener('chartjs:pre-connect', this._onPreConnect);
        this.element.addEventListener('chartjs:connect', this._onConnect);
    }

    disconnect() {
        // You should always remove listeners when the controller is disconnected to avoid side effects
        this.element.removeEventListener('chartjs:pre-connect', this._onPreConnect);
        this.element.removeEventListener('chartjs:connect', this._onConnect);
    }

    _onPreConnect(event) {
        // ...
    }

    _onConnect(event) {
        // ...
    }
}
```

your `mychart` controller listen to event dispatched by another Stimulus controller : the Symfony ux original `symfony--ux-chartjs--chart` controller.

therefore it is essential that your custom component is loaded **before** the original component to be able to listen for events like `chartjs:connect`, `chartjs:init`, etc... otherwise the events will have already occurred when your custom controller registers the listeners


one implementation can be:

```js
// assets/bootstrap.js
import {
  startStimulusApp,
  registerControllers,
} from "vite-plugin-symfony/stimulus/helpers";

// any file name as long as it doesn't match the regular expression: './controllers/*_(lazy)\?controller.[jt]s(x)\?'
import mychart from "./controllers/mychart_eagercontroller";
const app = startStimulusApp();

app.register('mychart', mychart)

registerControllers(app, import.meta.glob('./controllers/*_(lazy)\?controller.[jt]s(x)\?'))
```

```json
// assets/controllers.json
{
    "controllers": {
        "@symfony/ux-chartjs": {
            "chart": {
                "enabled": true,
                "fetch": "lazy"
            }
        },
    }
}
```

If your issue is still not resolved, can you tell me the steps to follow and the exact content of your files to reproduce your issue?

good evening

**Comment by Gerben321** [comment]
Thanks a lot for the explanation. Makes a lot of sense. I think this would solve it, but I've built my code differently now, and I am trying to move away from Symfony UX stuff and do it more natively. At first I built my chart with the Symfony UX package. Set up the data and options in the controller, and used the render_chart method to render it. On top of that I used controllers to change things like the tooltips and some other fancy stuff.

But changing away from Webpack Encore to Vite, and using this wonderful bundle has made me realise I'm better of creating the Chart in a regular JS file with a separate 'entry' in the Vite config and include that in my HTML. Then it just loads the Chart from the native JS way with a regular array from my controller. The Symfony UX project sounds easy and works fine, but it limits in a way if you want to go more in specific details, or you have to work in ugly workarounds.

Anyway, thanks again for your time. I'm sure this is the solution so I'll make it as done.

**Comment by lhapaipai** [comment]
> But changing away from Webpack Encore to Vite, and using this wonderful bundle has made me realise I'm better of creating the Chart in a regular JS file with a separate 'entry' in the Vite config and include that in my HTML.

I totally agree with you...
